theme:           jekyll-theme-cayman
title:           Guess the Number
description:     Try to find the number using various hints within the guess limit
is_user_page:    false
is_project_page: true
show_downloads:  true
